### PR TITLE
refresh Waypoints on comment load or new dweet form slide-down

### LINKED ISSUE #194: Autoplay doesn't work properly after long comment threads have loaded
After loading all comments on a long comment thread, scrolling down starts playing the dweets earlier, and stops playing them while they're in the middle of the screen.

To reproduce in prod:
1. Go to top
2. Find a dweet with many comments (for instance https://www.dwitter.net/d/1494)
3. Expand the comment thread.
4. Scroll further down.

### PR DESCRIPTION
**Pull request by tbroadley**
Closes #194.

With this change, [`Waypoint.refreshAll`](http://imakewebthings.com/waypoints/api/refresh-all/) is called whenever the layout of the page is updated (i.e. whenever comments are loaded or the new dweet form slides down).

### CODE REVIEW

File: dwitter/static/js/ajax-handling.js [hunk 1]
```diff
@@ -64,7 +64,10 @@ var loadComments = function() {
       }
       new_comment_list += getCommentHTML(comment);
     }
-    $comment_section[0].innerHTML = new_comment_list + $comment_section[0].innerHTML;
+    $(comment_section)
+      .html(new_comment_list + comment_section.innerHTML)
+      .promise()
+      .done(Waypoint.refreshAll);
```
Comment (tbroadley) [inline dwitter/static/js/ajax-handling.js]: Since the comment section's HTML is updated asynchronously, we need to wait until the update is finished before calling `Waypoint.refreshAll`. This is accomplished by converting the call to `html` into a promise, then waiting for the promise to resolve.
